import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import PageLoader from "./_components/PageLoader";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`body ${inter.className} bg-gray-100`}>
          <Toaster position="top-right" />
          <ClerkLoading>
            <PageLoader />
          </ClerkLoading>
          <ClerkLoaded>
            <Providers>{children}</Providers>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
